<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>StarDo</AssemblyName>
    <RootNamespace>StarDo</RootNamespace>
    <EnableHarmony>false</EnableHarmony>
    <GamePath>C:\Games\Stardew Valley</GamePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
